### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/infografia-Sandra631#2]
[Ciclo de vida del desarrollo de un de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Sandra631/files/7132874/Ciclo.de.vida.del.desarrollo.de.un.de.software.pdf)

**Comment by bg55-a** [comment]
reviso adolfo german vasquez rojas 
100 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
